mysite/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()
urlpatterns = patterns('',

    # Uncomment the next line to enable the admin:
    url(r'^rsvp/', include('rsvp.urls')),
    url(r'^admin/', include(admin.site.urls)),
   	# url(r'^rsvp/', include('rsvp.urls')),
   	url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT,} ),
	url(r'^', include('posts.urls')),
)

rsvp/urls.py
from django.conf.urls import patterns, url
from rsvp.forms import GuestAuth, GuestForm, GuestAttending, GuestChoice, PartyChoice
from posts.models import Post
# Uncomment the next two lines to enable the admin:
urlpatterns = patterns('rsvp.views',
    # Examples:
    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
	url(r'^$', 'GuestAuthView', name='GuestAuth'),
	url(r'attending/$', 'GuestAttendanceView', name='GuestAttending'),
	url(r'yes/$', 'GuestVerifyView', name='GuestVerify'),
	url(r'request/$', 'RequestView', name='RequestView'),
	url(r'confirm/$', 'GuestConfirmView', name='Confirm'),
	url(r'reports/$', 'ReportView', name='ReportView'),

    # url(r'^(?P<string>\w+)/$', 'page', name='page'),
)

rsvp/models.py
from django.db import models
from django.forms import ModelForm
import datetime

class Guest(models.Model):		# we create a model for a single guest
	first_name = models.CharField(max_length=45, null=True, blank=True)
	last_name = models.CharField(max_length=45, null=True, blank=True)
	attending = models.BooleanField(blank=True)
	primary_email = models.EmailField(max_length=254, null=True, blank=True)
	street_addr = models.CharField(max_length=255, null=True, blank=True)
	city = models.CharField(max_length=255, null=True, blank=True)
	state = models.CharField(max_length=2, null=True, blank=True)
	zip_code = models.IntegerField(max_length=5, null=True, blank=True)
	primary = models.NullBooleanField(null=True, blank=True)
	events = models.ManyToManyField('Event', null=True, blank=True)
	hotel = models.ForeignKey('Hotel', null=True, blank=True)
	bride = models.BooleanField(default=False)
	groom = models.BooleanField(default=False)

	class Meta:
		ordering = ['-last_name', '-first_name']

	def __unicode__(self):
		return u'%s %s' % (self.first_name, self.last_name)

class Abstract(models.Model):
	name = models.CharField(max_length=255)

	class Meta:
		abstract = True

	def __unicode__(self):
		return u'%s' % self.name 

class Location(models.Model):
	name = models.CharField(max_length=255)
	distance = models.DecimalField(decimal_places=1, max_digits=3)

	def __unicode__(self):
		return u'%s' % self.name

class Table(Abstract):
	pass

class Event(models.Model):
	name = models.CharField(max_length=255)
	location = models.ForeignKey(Location, null=True)
	notes = models.TextField(blank=True, null=True)
	date = models.DateTimeField(default=datetime.datetime(2014, 8, 1, 00))

	class Meta:
		ordering = ['date']

	def __unicode__(self):
		date = self.date.strftime("%A")
		name = self.name
		return u'%s: %s' % (date, name)

class Hotel(Abstract):
	total_guest_count = models.IntegerField(max_length=2, null=True, blank=True)
	url = models.URLField(null=True, blank=True)
	notes = models.TextField()
	block = models.BooleanField(default=False, blank=True)

class Party(models.Model):
	name = models.TextField(null=True, blank=True)
	guests = models.ManyToManyField(Guest)
	max_size = models.IntegerField(default=1)
	responded = models.BooleanField(default=False)
	gift = models.TextField(null=True, blank=True)

	def __unicode__(self):
		return u'%s' % self.name

class Song(models.Model):
	title = models.CharField(max_length=500)
	artist = models.CharField(max_length=500)
	comment = models.TextField(blank=True, null=True)
	requested_by = models.ManyToManyField(Guest, null=True, blank=True)
	votes = models.IntegerField(default=1)

	def __unicode__(self):
		return u'%s, %s' % (self.title.capitalize(), self.artist.capitalize())

rsvp/forms.py
# forms.py
from django import forms
from django.forms import ModelForm
from django.forms.models import modelformset_factory, BaseModelFormSet
import html5.forms.widgets as html5_widgets
from rsvp.models import Guest, Hotel, Event, Party, Song

forms.DateInput.input_type="date"
forms.DateTimeInput.input_type="datetime-local"

class SongRequest(ModelForm):
	class Meta:
		model = Song

class GuestAuth(forms.Form):
	first_name = forms.CharField(max_length=100)
	last_name = forms.CharField(max_length=100)
	zip_code = forms.IntegerField()
	invitation_number = forms.IntegerField()

class AttendanceForm(ModelForm):
	class Meta:
		model =Guest
		fields = ('first_name', 'last_name', 'attending')

class GuestAttending(ModelForm):
	class Meta:
		model = Guest
		fields = ['attending']

	attending = forms.BooleanField(label='Check the box if you are attending.')

class GuestForm(ModelForm):
	class Meta:
		model = Guest

class GuestHotelForm(ModelForm):
	class Meta:
		model = Guest
		exclude = ['zip_code', 'first_name', 'last_name', 'attending', 'primary_email', 'street_addr', 'city', 'state', 'primary', 'bride', 'groom']

class GuestChoice(forms.Form):
	guests = Guest.objects.all()
	guest = forms.ChoiceField(choices=guests)

class PartyChoice(forms.Form):
	parties = Party.objects.all()
	party = forms.ChoiceField(choices=parties)

rsvp/views.py
import datetime
from django.http import HttpResponse, HttpResponseRedirect
from django.http import HttpResponseServerError, HttpResponseForbidden
from django.core.urlresolvers import reverse
from django.shortcuts import render, get_object_or_404, render_to_response
from django.conf import settings
from django.forms.formsets import formset_factory
from django.forms.models import modelformset_factory, BaseModelFormSet
from django.contrib.formtools.wizard.views import CookieWizardView
from rsvp.models import Guest, Hotel, Event, Party, Song
from rsvp.forms import SongRequest, GuestAuth, GuestForm, GuestAttending
from rsvp.forms import GuestHotelForm, GuestChoice, PartyChoice
from django.views.decorators.cache import cache_page
bride = Guest.objects.get(bride=True)
groom = Guest.objects.get(groom=True)

# @cache_page(60, cache='default', key_prefix='rsvp')
def GuestAuthView(request):
	global bride
	global groom
	error = None
	if request.session.get('pk') is not None:
		return HttpResponseRedirect('attending/')
	if request.method == 'POST':
		form = GuestAuth(request.POST)
		if form.is_valid():
			first = form.cleaned_data['first_name']
			last = form.cleaned_data['last_name']
			zip_code = form.cleaned_data['zip_code']
			party = form.cleaned_data['invitation_number']
			key = str(first) + str(last) + str(zip_code) + str(party)
			c = Guest.objects.get(first_name=first, last_name=last) 
			c_first = c.first_name
			c_last = c.last_name
			c_zip = str(c.zip_code)
			c_party = c.party_set.all()
			check = str(c_first) + str(c_last) + str(c_zip) + str(c_party[0].pk)
			import hashlib
			key = hashlib.sha224(key).hexdigest()
			check = hashlib.sha224(check).hexdigest()
			if	key == check:
				request.session['pk'] = c.pk
 				return HttpResponseRedirect('attending/')
			else:
				error = 'Something went wrong, double check all your fields are correct and try again.'
				return render(request,'auth.html', {
					'form' : form,
					'bride' : bride,
					'groom' : groom,
					'error' : error,
					})

	else:
		form = GuestAuth()

	return render(request, 'auth.html', {
		'form' : form,
		'bride' : bride,
		'groom' : groom,
	})

# @cache_page(60, cache='default', key_prefix='rsvp')
def GuestAttendanceView(request):
	global bride
	global groom
	pk = request.session.get('pk')
	guest = Guest.objects.get(pk=pk)
	party = guest.party_set.all()[0]
	size = party.max_size
	partyFormset = modelformset_factory(Guest,
		fields=['first_name', 'last_name', 'attending'],
		max_num=size
	)
	if request.method == 'POST':
		partyForm = partyFormset(request.POST)
		attendees = 0
		for p in partyForm:
			key = '%s-attending' % (p.prefix)
			if p.data.has_key(key) == False:
				attendees = attendees + 1
		if partyForm.is_valid():
			new_guest = partyForm.save()
			count = len(new_guest)
			count = count - 1
			if count >= 0:
				party.guests.add(new_guest[count])
			if attendees == size:
				return HttpResponseRedirect('/thanks/')
			else:
				return HttpResponseRedirect('yes/')
	elif request.method == 'GET':
		partyForm = partyFormset(queryset=party.guests.all())
	return render(request, 'attending.html', {
		'partyForm' : partyForm,
		'guest' : guest,
		'bride' : bride,
		'groom' : groom,
	})

# @cache_page(60, cache='default', key_prefix='rsvp')
def GuestVerifyView(request):
	global bride
	global groom
	pk = request.session.get('pk')
	guest = Guest.objects.get(pk=pk)
	party = guest.party_set.all()[0]
	others = Guest.objects.filter(party=party.pk)
	if request.method == 'POST':
		guestform = GuestHotelForm(request.POST, instance=guest)
		if guestform.is_valid():
			guestform = guestform.save()
			events = guest.events.all()
			for other in others:
				other.hotel = guest.hotel
				other.street_addr = guest.street_addr
				other.city = guest.city
				other.state = guest.state
				other.zip_code = guest.zip_code
				for event in events:
					other.events.add(event.pk)
				other.save()
			return HttpResponseRedirect('request/')

	elif request.method == 'GET':
		guestform = GuestHotelForm(instance=guest)
	else:
		guestform = GuestHotelForm()
	block = Hotel.objects.filter(block=True)
	hotel = block[0]
	wedding = bride.last_name + groom.last_name

	return render(request, 'logistics.html', {
		'guestform' : guestform,
		'guest' : guest,
		'party' : party,
		'bride' : bride,
		'groom' : groom,
		'hotel' : hotel,
		'wedding' : wedding,
	})

# @cache_page(60, cache='default', key_prefix='rsvp')
def RequestView(request):
	global bride
	global groom
	pk = request.session.get('pk')
	guest = Guest.objects.get(pk=pk)
	RequestFormSet = modelformset_factory(
		Song,
		fields=['title', 'artist'],
		max_num=5, extra=5
	)
	if request.method == 'POST':
		formset = RequestFormSet(request.POST)
		if formset.is_valid():
			objects = formset.save(commit=False)
			for song in objects:
				song.title = song.title.lower()
				song.artist = song.artist.lower()
				requested = Song.objects.filter(
					title=song.title,
					artist=song.artist
				)
				if len(requested) == 1:
					song = Song.objects.get(
						title=song.title,
						artist=song.artist
					)
				else:
					song = Song.objects.create(
						title=song.title,
						artist=song.artist
					)
				song.requested_by.add(guest)
				song.votes = song.requested_by.count()
				song.save()
		return HttpResponseRedirect('confirm/');
	else:
		requested = Song.objects.filter(requested_by=Guest.objects.get(pk=pk))
		if len(requested) > 0:
			formset = RequestFormSet(queryset=requested)
		else:
			formset = RequestFormSet(queryset=Song.objects.filter(id=0))
	return render(request, 'request.html', { 
		'formset' : formset,
		'bride' : bride,
		'groom' : groom,
	 })

# @cache_page(60, cache='default', key_prefix='rsvp')
def GuestConfirmView(request):
	global bride
	global groom
	pk = request.session.get('pk')
	guest = Guest.objects.get(pk=pk)
	events = guest.events.all()
	party = guest.party_set.all()[0]
	members = party.guests.all()
	m = members.filter(attending=True)
	hotel = guest.hotel
	return render(request, 'confirm.html', {
		'guest' : guest,
		'events' : events,
		'party' : party,
		'members' : m,
		'bride' : bride,
		'bride' : bride,
		'groom' : groom,
		'hotel' : hotel,
		} )

def ReportView(request):
	global bride
	global groom
	guests = GuestChoice()
	parties = PartyChoice()
	return render(request, 'report-landing.html', {
		'guests' : guests,
		'parties' : parties,
		'bride' : bride,
		'groom' : groom,
		})

rsvp/templates/attending.html
{% extends "base.html" %}
{% load i18n %}

{% block head %}
{% endblock %}

{% block content %}
<script type="text/javascript">
</script>
<section id="content" class="row-fluid wisc">
	<div class="span1 pull-left hidden-phone">&nbsp;</div>
	<article class="span7 pull-left" id="body-text">

		<h3>Welcome, {{ guest }}!</h3>
		<form class="attending-form" action="" method="post">
			{{ partyForm.management_form }}
			{% csrf_token %}
		<p>We're pretty sure these are the people who are in your party. Feel free to correct us or fill in any missing information. <em>Also, make sure to check the "attending" box for each guest.</em></p>
			<div id="init">
				{% for p in partyForm %}
					<div id="guest-{{ forloop.counter }}" class="labels pull-left">
						<h4>Guest {{ forloop.counter }}</h4>
						{{ p.as_p }}
					</div>
				{% endfor %}
			</div>
			<button class="btn pull-left" type="submit">Submit</button>

		</form>
	</article>

{% endblock %}

rsvp/templates/auth.html
{% extends "base.html" %}
{% load i18n %}

{% block head %}
{% endblock %}

{% block content %}
		<section id="content" class="row-fluid wisc">
		<div class="span1 pull-left hidden-phone">&nbsp;</div>
		<article class="span7 pull-left" id="body-text">
			{% if error %}
				<p class="alert">{{ error }}</p>
			{% endif %}
			<h3>RSVP Here!</h3>
			<div class="step-one">
				<p>Thanks for RSVPing, this should only take a couple minutes. First, we need to look you up in our system before we continue. Your invitation should have an insert card, go ahead and find that.</p>
			</div>
			<div class="step-two">
				<p>Got it? Good, now you should see an "invitation number" on that card. Enter that number in the field below.</p>
			</div>
			<div>
				<p>For the first and last names, use a name printed on your envelope exactly as it appears. If the envelope says Dan, for example, do not use Daniel. If your name is spelled wrong (sorry!) spell it wrong here. You can correct us on the next screen; and again, sorry.</p>
			</div>
			<form action="" method="post">{% csrf_token %}
				{{ form.as_p }}
				<button class="btn" type="submit">Submit</button>
			</form>
		</article>

{% endblock %}

rsvp/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<!--[if IE 7]>
<html class="ie ie7" >
<link rel="stylesheet" href="css/ink-ie7.css" type="text/css" media="screen" title="no title" charset="utf-8" />
<![endif]-->
<!--[if IE 8]>
<html class="ie ie8" >
<![endif]-->
<!--[if !(IE 7) | !(IE 8)  ]><!-->
<html>
<!-- Thanks for visiting, feel free to critique my html, but don't let it distract you from what you came for, learning about our wedding. -->
<!--<![endif]-->
	<head>
		<title>{% block title %}{% endblock %}</title>
		<link rel="profile" href="http://gmpg.org/xfn/11" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<link href="{{ STATIC_URL }}css/bootstrap.min.css" rel="stylesheet" media="screen">

		<link href="{{ STATIC_URL }}css/bootstrap-responsive.css" rel="stylesheet">
		<link rel="stylesheet" href="{{ STATIC_URL }}css/styles.css" type="text/css" media="screen" title="custom-styles" charset="utf-8" />
		<!--[if lt IE 9]>
		<script src="/js/html5.js" type="text/javascript"></script>
		<![endif]-->
	</head>
	<style type="text/css">
	div#main-nav ul ul {
		display: none;
	}

	div#main-nav li:hover > ul {
		display: block;
	}


	</style>
	<body onload="initialize()">
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-48081677-1', 'harmsboone.org');
  ga('send', 'pageview');

</script>
		<div class="container-fluid">

			<header class="row-fluid">
			<div class="span1"></div>
			<div class="span12">
				<h1 class="hidden-phone">Danielle Harms | Greg Boone</h1>
				<h1 class="visible-phone">Danielle & Greg: North Country Wedding</h1>
				<h2 class="hidden-phone">A North Country Wedding.</h2>
			</div>
			<div id="main-nav" class="hidden-phone span12">
				<ul class="nav">
					<li class="pull-left"><a href="/">Home</a></li>
					<li class="pull-left"><a href="/location/">Destination</a>
						<ul class="nav pull-left">
							<li class=""><a href="/directions/">Getting there</a></li>
							<li class=""><a href="/lodging/">Where to stay</a></li>
							<li class=""><a href="/activities/">What to do</a></li>
						</ul>
					</li>
					<li class="pull-left"><a href="/the_couple/">Cast</a></li>
					<li class="pull-left"><a href="/the_party/">Crew</a></li>
					<li class="pull-left"><a href="/rsvp/">RSVP</a></li>
				</ul>
			</div> <!-- main-nav -->
			</header>

					{% block content %}
					{% endblock %}

				<div id="sidebar" class="span3 pull-left">
				<h4>Handy links:</h4>
				<ul class="nav nav-list">
					<li><a href="/">Home</a></li>
					<li><a href="/the_couple/">About The Couple</a></li>
					<li><a href="/the_couple/">About Danielle</a></li>
					<li><a href="/the_couple/">About Greg</a></li>
					<li><a href="/the_party/">The Wedding Party</a></li>
					<li><a href="/location/">What the heck is a Mantowish!?</a></li>
					<li><a href="http://www.chippewaretreat.com/">Chippewa Retreat</a></li>
					<li><a href="/directions/">Directions</a></li>
					<li><a href="/lodging/">Where to Stay</a></li>
					<li><a href="/activities/">What to do</a></li>
					<li><a href="http://harmsboone.org/">Danielle and Greg's travels.</a></li>
				</ul>

				</div>
				<div class="span1 pull-right">&nbsp;</div>
			</section>
			
			<footer class="row-fluid pull-left hidden-phone">
			<ul class="span4 nav nav-list">
				<li><a href="http://wedding.harmsboone.org">A North Country Wedding</a></li>
				<li><a href="http://wedding.harmsboone.org">Danielle Harms and Greg Boone</a></li>
				<li><a href="http://www.youtube.com/watch?v=D2VsUCYw_JU">Some humor</a></li>
				<li><a href="http://flickr.com/photos/daniellemharms">Flickr</a></li>
			</ul>
			<ul class="span4 nav nav-list">
				<li><a href="/location/">Location</a></li>
				<li><a href="/directions/">Getting there</a></li>
				<li><a href="/lodging/">Where to stay</a></li>
				<li><a href="/activities/">What to do</a></li>
			</ul>
			<ul class="span4 nav nav-list">
				<li><a href="/the_couple/">Cast</a></li>
				<li><a href="/the_party/">Crew</a></li>
				<li><a href="http://harmsboone.org">Learn more.</a></li>
				<li><a href="#"> 2013 HarmsBoone.org</a></li>
			</ul>
			</footer>

		</div>

		<script type="text/javascript" src="js/bootstrap.min.js"></script>
		<script type="text/javascript">
		</script>

	</body>
</html>

rsvp/templates/confirm.html
{% extends "base.html" %}
{% load i18n %}

{% block head %}
{% endblock %}

{% block content %}
<script type="text/javascript">
</script>
<section id="content" class="row-fluid dlh">
		<div class="span1 pull-left hidden-phone">&nbsp;</div>
		<article class="span7 pull-left" id="body-text">

			<h3>See you in August, {{ guest.first_name }}</h3>
			<p>Let's take a minute and verify everything is correct. Check the details below and <a href="/rsvp/attending">click here if you need to start over</a>.</p>
				<ul id="init">
					{% if guest.attending == False %}
						<li>Your party will not be attending the wedding.</li>
					{% else %}
						<li>Your party will be attending the wedding.</li>
					{% endif %}
					<li>Your party contains these guests:</li>
					<ul>
						{% for member in members %}
						<li>{{ member }}</li>
						{% endfor %}
					</ul>
					<li>We have you down for the following events:</li>
					<ul>
						{% for event in events %}
						<li>{{ event }}</li>
						{% endfor %}
					</ul>
				</ul>
				<p>Finally, we have you staying at {{ guest.hotel }}</p>
				<p>Need to make a change? Use your browser's back button to go back a page.</p>
				<a href="/thanks/" class="btn btn-block">All Correct? Click here!</a>

			</form>
		</article>

{% endblock %}

rsvp/templates/contact.html
<form action="" method="post">{% csrf_token %}
	{{ form.as_p }}
	<input type="submit" value="Submit" />
</form>

rsvp/templates/logistics.html
{% extends "base.html" %}
{% load i18n %}

{% block head %}
{% endblock %}

{% block content %}
<script type="text/javascript">
</script>
<section id="content" class="row-fluid stock">
		<div class="span1 pull-left hidden-phone">&nbsp;</div>
		<article class="span7 pull-left" id="body-text">
			<form action="" method="post">{% csrf_token %}
				<div id="lodging" class="">
					<h3>Where are you staying?</h3>
					<div id="gsl_choice">
						<p>We have a block at {{ hotel.name }}. If you would like to stay there, please contact them directly and mention you are part of the {{ wedding }} wedding. There are many rooms available but summer is a busy season so we urge you to book as soon as possible. If you know where you are staying, choose one of the hotels listed or leave this field blank.</p>
						{{ guestform.hotel.errors }}
						{{ guestform.hotel }}
					</div>
				</div>
				<div id="events" class="">
					<h3>Special Events</h3>
					<p>We know that many of our guests are traveling a long way to be at our wedding. We're hosting events throughout the weekend, <a href="/activities">see the activies page for more information</a>. Please let us know which of the events you would like to attend. Hold the control or command key to select multiple events.</p>
					{{ guestform.events.errors }}
					{{ guestform.events }}
					<button class="btn next" type="submit">Submit</button>
				</div>
				<div id="sorry" class="hidden">
					<p>Sorry to hear you can't make it! Feel free to hang out here on the website for a while. You can read <a href="the_cast" >about the bride and the groom</a>, <a href="crew">the wedding party</a>, or go <a href="wedding.harmsboone.org">back to the home page</a>. Did you do this accidentally? Click here to <a href="/rsvp">RSVP again</a>.</p>
				</div>

			</form>
		</article>
		<script type="text/javascript">
		// window.onload = function hide_forms() {
		// 	$("#summary li.other > span.events").hide();

		// 	$("#id_attending").click(function() {
		// 		$(this).toggleClass('checked');
		// 	});

		// 	$( "a.btn").click(function(){
		// 		var clicked = $(this);
		// 		var attending = $("#id_attending")
		// 		if ( attending.hasClass('checked') ) {
		// 			var item = clicked.attr("href");
		// 		} else {
		// 			var item = $("#sorry");
		// 		}

		// 		var current = $(this).parent();
		// 		div_toggle(current);
		// 		div_toggle(item);
		// 	});
		// }

		// $("#guests a.next").click( function() {
		// 	$("<ul></ul>").appendTo($("#summary > ul > li.guests"));
		// 	var guests = $("#guests > p > input[type='text']");
		// 	jQuery.each(guests, function( i, val ) {
		// 		if ( $(val).attr("id").indexOf('first_name') > 0){ 
		// 			var element = $("#summary > ul > li.guests > ul");
		// 			if ($(val).val().length > 0) {
		// 				text = $(val).val();
		// 				$("<li>" + text + "</li>").appendTo( element );
		// 			}
		// 		}
		// 	});
		// 	console.log($("summary > ul > li.guests > ul"));
		// 	console.log("Guests added to summary. Starting to add hotel information.");
		// });
		
		// $("#id_stay_here_0").change( function() {
		// 		var item = $("#else_hotel");
		// 		if ( item.hasClass('hidden') == true ) {	
		// 			div_toggle($(item) );
		// 		}
		// 		if ( $("#if_chippewa").hasClass('hidden') == false ) {
		// 			div_toggle($("#if_chippewa"));
		// 		}
		// 	});

		// $("#id_stay_here_1").change( function() {
		// 	var item = $("#if_chippewa");
		// 	if ( item.hasClass('hidden') == true ) {
		// 		div_toggle($(item) );
		// 		$("select#id_hotel > option:eq(1)").attr('selected', true);
		// 		add_hotel();
		// 	}
		// 	if ( $("#else_hotel").hasClass('hidden') == false ) {
		// 		div_toggle($("#else_hotel"));
		// 	}
		// });
		
		// $("#lodging > .next").click( function() {
		// 	var arr = $("#id_arriving").val();
		// 	var dep = $("#id_departing").val();
		// 	var diff = calc_date_between(arr, dep);
		// 	var target = $("#summary > ul > li.hotel > span.nights");
		// 	add_date_diff(diff, target);
		// });

		// $("#lodging > .back").click( function() {
		// 	$("#summary > ul > li.guests > ul").remove();
		// 	console.log('guests > ul emptied');
		// 	console.log($("summary > ul > li.guests"));
		// });

		// $("#id_hotel").change( function() {
		// 	add_hotel();
		// 	$("#summary > ul > li.hotel > span.nights").remove();
		// 	console.log("Hotel info added, nights removed.");
		// });

		// $("#events > .next").click( function() {
		// 	var checkedEvents = $("#events input");
		// 	checkedEvents.each(function(i, v) {
		// 		if ( $(v).is(":checked") ) {
		// 			var label = $(this).parent();
		// 			var text = $(label).text();
		// 			$("#summary li.other > span.events").prepend(text + ", ");
		// 		}
		// 	});
		// 	if ( checkedEvents.length >= 1 ) {
		// 		$("#summary li.other > span.events").show();
		// 		console.log("events should be showing.");
		// 	}
		// });

		// $("#events > .back").click( function() {
		// 	$("#summary li.hotel > span.nights").empty();
		// 	$("#summary li.hotel > span.name").empty();
		// });

		// $("#summary > .back").click( function() {
		// 	$("#summary > ul > li.other > span.events").empty();
		// })

		// function add_events(checked) {
		// 	var value = checked.html;
		// 	value.appendTo($("li.other"))
		// 	console.log(value);
		// }

		// function div_toggle(item) {
		// 	$(item).toggleClass("hidden");
		// }

		// function ins_html_li_vals(object, element) {
		// 	$("<li>" + object.val() + "</li>").appendTo( element );
		// 	console.log("object: " + object.html());
		// 	console.log("element: " + element.html());
		// }
		
		// function add_hotel() {
		// 	var hotel_span = $("#summary > ul > li.hotel span.name");
		// 	selected = $("#id_hotel option:selected").text();
		// 	hotel_span.text(selected);
		// 	console.log('Guest is staying at ' + selected + ".");
		// }

		// function calc_date_between(arr, dep) {
		// 	var diff = (Date.parse(dep)-Date.parse(arr));
		// 	var diff = diff/(1000*60*60*24);
		// 	console.log("Diff is " + diff);
		// 	return diff;
		// }

		// function add_date_diff(diff, target) {
		// 	$(target).append(diff + " nights");
		// }
		</script>
{% endblock %}

rsvp/templates/report-landing.html
{% extends "base.html" %}
{% load i18n %}

{% block head %}
{% endblock %}

{% block content %}
		<section id="content" class="row-fluid wisc">
		<div class="span1 pull-left hidden-phone">&nbsp;</div>
		<article class="span7 pull-left" id="body-text">
			<form action="" method="post">{% csrf_token %}
				{{ guests }}
				{{ parties }}
				<button class="btn" type="submit">Submit</button>
			</form>
		</article>

{% endblock %}

rsvp/templates/request.html
{% extends "base.html" %}
{% load i18n %}

{% block head %}
{% endblock %}

{% block content %}
<script type="text/javascript">
</script>
<section id="content" class="row-fluid stock">
		<div class="span1 pull-left hidden-phone">&nbsp;</div>
		<article class="span7 pull-left" id="body-text">
			<h2>Request a song!</h2>
			<h3>(Or five)</h3>
			<p>Is there a song that would get you on the floor? Let us know! Each guest can request up 5.</p>
			<form action="" method="post">{% csrf_token %}
				{{ formset }}
				<button class="btn next" type="submit">Submit</button>
			</form>
		</article>
{% endblock %}